<script src="./assets/jquery-1.11.2.min.js" type="text/javascript"></script>
<script src="./assets/bootstrap.min.js" type="text/javascript"></script>
<script src="./assets/jquery.appear.js" type="text/javascript"></script>
<script src="./assets/jquery.mixitup.min.js" type="text/javascript"></script>
<script src="./assets/owl.carousel.min.js" type="text/javascript"></script>
<script src="./assets/jquery.flexslider-min.js" type="text/javascript"></script>
<script src="./assets/jquery.inview.min.js" type="text/javascript"></script>
<script src="./assets/jquery.knob.min.js" type="text/javascript"></script>
<script src="./assets/jquery.cookie.js" type="text/javascript"></script>
<script src="./assets/jquery.ratyli.js" type="text/javascript"></script>
<script src="./assets/modernizr.custom.js" type="text/javascript"></script>
<script src="./assets/contact_scripts.js" type="text/javascript"></script>
<script src="./assets/scripts.js" type="text/javascript"></script>
